// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToysAndGamesAPI.Data;

#nullable disable

namespace ToysAndGamesAPI.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToysAndGamesAPI.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgeRestriction")
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeRestriction = 0,
                            Company = "Mattel",
                            Description = "Popular Board Game",
                            Name = "Monopoly",
                            Price = 70m
                        },
                        new
                        {
                            Id = 2,
                            AgeRestriction = 5,
                            Company = "Mattel",
                            Description = "Action Figure with sounds and light",
                            Name = "Iron Man Action Figure",
                            Price = 80m
                        },
                        new
                        {
                            Id = 3,
                            AgeRestriction = 8,
                            Company = "Mattel",
                            Description = "Beautiful and creepy doll at once",
                            Name = "Monster High doll",
                            Price = 30m
                        },
                        new
                        {
                            Id = 4,
                            AgeRestriction = 5,
                            Company = "Hasbro",
                            Description = "Dark Knight's most famous gadget!",
                            Name = "Batmobile",
                            Price = 180m
                        },
                        new
                        {
                            Id = 5,
                            AgeRestriction = 4,
                            Company = "Sony",
                            Description = "Sony famous console",
                            Name = "Playstation 5",
                            Price = 400m
                        },
                        new
                        {
                            Id = 6,
                            AgeRestriction = 18,
                            Company = "Naughty Dog",
                            Description = "Great Videogame from Naughty Dog!",
                            Name = "The last of Us 2",
                            Price = 60m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
